name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports: ['27017:27017']

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Fix node-pre-gyp permission
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          # Convert line endings in case they are Windows-style
          dos2unix ./node_modules/.bin/node-pre-gyp || true
          # Grant execution permission
          chmod +x ./node_modules/.bin/node-pre-gyp || true

      - name: Rebuild bcrypt from source
        run: npm rebuild bcrypt --build-from-source

      - name: Run tests
        run: npm test
        env:
          MONGO_URI: mongodb://localhost:27017/book-lending
          JWT_SECRET: "secret"
